theme: minima
title: Strobosaur's cyberspace junkyard
author: strobosaur
email: confidential for now
description: > # this means to ignore newlines until "baseurl:"
  Chronicle of the trials and tribulations of an aspiring machine poet

github_username: strobosaur

show_excerpts: true # set to false to remove excerpts on the homepage
